`define ADDR_GPI_0      0
`define ADDR_GPI_1      1
`define ADDR_GPI_2      2
`define ADDR_GPI_3      3
`define ADDR_GPI_4      4
`define ADDR_GPI_5      5
`define ADDR_GPI_6      6
`define ADDR_GPI_7      7
`define ADDR_GPO_0      8
`define ADDR_GPO_1      9
`define ADDR_GPO_2      10
`define ADDR_GPO_3      11
`define ADDR_GPO_4      12
`define ADDR_GPO_5      13
`define ADDR_GPO_6      14
`define ADDR_GPO_7      15
`define ADDR_UART_RXD   16
`define ADDR_UART_TXD   17
`define ADDR_UART_CTL   18
`define ADDR_TMR_0      19
`define ADDR_TMR_1      20
`define ADDR_TMR_2      21
`define ADDR_TMR_3      22
`define ADDR_TMR_TRIG   23
`define ADDR_TMR_RST    24

`define RESET_VECTOR    32

`define OP_HALT     0
`define OP_LD       1
`define OP_ST       2
`define OP_STL      3
`define OP_LDL      4
`define OP_MOV      5
`define OP_ADD      6
`define OP_SUB      7
`define OP_AND      8
`define OP_OR       9
`define OP_XOR      10
`define OP_SFL      11
`define OP_SFR      12
`define OP_INC      13
`define OP_DEC      14
`define OP_EQL      15
`define OP_GTH      16
`define OP_LTH      17
`define OP_INV      18
`define OP_BRZ      19
`define OP_BRNZ     20
`define OP_JMP      21

`define RAM_ADDR_BITS   13
